export const Routes = {
  Home: "/",
  Profile: "/thong-tin-ca-nhan",
  Favourite: "/xe-yeu-thich",
  AppoinmentHistory: "/thoi-gian-hen",
  ProductSold: "/san-pham",
  About: "/gioi-thieu",
  CarDetails: "/chi-tiet-san-pham/:id/:slug",
  Login: "/dang-nhap",
  Register: "/dang-ky",
  Services: "/dich-vu-cham-soc-xe",
  Articles: "/tin-tuc",
  ArticleSave: "/bai-viet-da-luu",
  NewsDetails: "/chi-tiet-bai-viet/:id/:slug",
  ShowRoom: "/showroom",
  Contact: "/lien-he-showroom",
  ContactHistory: "/lich-su-lien-he",
  ForgotPassword: "/quen-mat-khau",
  ResetPassword: "/reset-password",
  //Admin
  Manager: "/admin/quan-ly/:slug",
  AssignManager: "/admin/quan-ly/phan-cong-nhan-vien",
  UsersManager: "/admin/quan-ly/nguoi-dung",
  ArtilcesManager: "/admin/quan-ly/bai-viet",
  CarsManager: "/admin/quan-ly/xe-o-to",
  DashBoardAdmin: "/admin/quan-ly/dasboard",
  ContactAssign: "/admin/quan-ly/phan-bo-contact",
  AppointmentAdmin: "/admin/quan-ly/lich-hen-khach-hang",
  //Staff
  CarStaff: "/staff/quan-ly/xe-duoc-phan-cong",
  AppointmentStaff: "/staff/quan-ly/lich-hen-khach-hang",
  MyContact: "/staff/quan-ly/my-contact",
  DashBoardStaff: "/staff/quan-ly/dasboard",
  ArticleStaff: "/staff/quan-ly/bai-viet",
};
export const hiddenFooterRoutes = [
  Routes.Login,
  Routes.Register,
  Routes.CarDetails,
];
